apiVersion: 1

datasources:
  - name: InfluxDB
    uid: DIY8fp-Vz
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    basicAuth: false
    isDefault: true
    jsonData:
      version: Flux
      organization: ${DOCKER_INFLUXDB_INIT_ORG}
      defaultBucket: ${DOCKER_INFLUXDB_INIT_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}

      